CREATE SCHEMA proyectofs
USE proyectofs
CREATE TABLE Users (
UserID BIGINT NOT NULL PRIMARY KEY,
Uname VARCHAR(50) NOT NULL,
PWordHash VARCHAR(60) NOT NULL);
CREATE TABLE TeamGroups (
GroupID BIGINT NOT NULL PRIMARY KEY,
Gname VARCHAR(50) NOT NULL,
UStatus JSON);
CREATE TABLE UserGroups (
UserID BIGINT NOT NULL,
GroupID BIGINT NOT NULL,
FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
FOREIGN KEY (GroupID) REFERENCES TeamGroups(GroupID) ON DELETE CASCADE);