CREATE SCHEMA proyectofs
USE proyectofs
CREATE TABLE users (
UserID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Uname VARCHAR(50) NOT NULL,
PWordHash VARCHAR(60) NOT NULL);
CREATE TABLE teamgroups (
GroupID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Gname VARCHAR(50) NOT NULL);
CREATE TABLE usergroups (
UserID BIGINT NOT NULL,
GroupID BIGINT NOT NULL,
URole ENUM('user','admin'),
UStatus TINYINT(1) NOT NULL,
FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
FOREIGN KEY (GroupID) REFERENCES TeamGroups(GroupID) ON DELETE CASCADE);